export default {
  superAdmin: {
    dashboard: { 
      view: true, 
      kpiCards:{show:true}, 
      quickView:{show:true}, 
      quickAction:{show:true}
    },
    users: { 
        view: true, 
        dashboard: { view: true, kpiCards:{show:true}, quickView:{show:true}, quickAction:{show:true} }, 
        addNew: {view:true},
        profile:  { view:true , general:{view:true}, specific:{view:true}, permissions:{view:true}, reservations:{view:true}, history:{view:true}},
        list: { view: true }, 
        history: { view: true },
    },
    vendors: { 
        view: true, 
        dashboard: { view: true, kpiCards:{show:true}, quickView:{show:true}, quickAction:{show:true} }, 
        profile:{view:true, general:{view:true}, specific:{view:true},admins:{view:true}, inventory:{view:true}, reservations:{view:true}, payments:{view:true}, history:{view:true}, docs:{view:true} },
        list: { view: true }, 
        globalInventory: { view: true }, 
        docs: { view: true },
    },
    employees: { 
        view: true, 
        dashboard: { view: true, kpiCards:{show:true}, quickView:{show:true}, quickAction:{show:true} }, 
        profile: { view: true, general:{view:true}, specific:{view:true}, permissions:{view:true}, history:{view:true}, docs:{view:true} } ,
        list: { view: true }, 
        history: { view: true }, 
        docs: { view: true },
    },
    booking: { view: true},
    financial: { view: true},
    content: { view: true},
    reports: { view: true},
    marketing: { view: true},
    pushNotification: { view: true},
    support: { view: true},
    systemSetting: { view: true},
    logSecurity: { view: true},
  },

  // admin: {
  //   dashboard: { view: true},
  //   users: { view: true},
  //   vendors: { view: true},
  //   employee: {view:true, },
  //   booking: { view: true},
  //   financial: { view: true},
  //   content: { view: true},
  //   reports: { view: true},
  //   marketing: { view: true},
  //   pushNotification: { view: true},
  //   support: { view: true},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // financialManager: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: false},
  //   employee: {view:false, },
  //   booking: { view: false},
  //   financial: { view: true},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: false},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // support: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: true},
  //   employee: {view:false, },
  //   booking: { view: true},
  //   financial: { view: true},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: true},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // operationManager: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: true},
  //   employee: {view:false, },
  //   booking: { view: true},
  //   financial: { view: false},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: false},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // contentManager: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: false},
  //   employee: {view:false, },
  //   booking: { view: false},
  //   financial: { view: false},
  //   content: { view: true},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: false},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // marketingManagement: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: false},
  //   employee: {view:false, },
  //   booking: { view: false},
  //   financial: { view: false},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: true},
  //   pushNotification: { view: true},
  //   support: { view: false},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // vendors: {
  //   dashboard: { view: true},
  //   users: { view: false},
  //   vendors: { view: true},
  //   employee: {view:false, },
  //   booking: { view: true},
  //   financial: { view: false},
  //   content: { view: false},
  //   reports: { view: true},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: true},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // },

  // technicalAdmin: {
  //   dashboard: { view: false},
  //   users: { view: false},
  //   vendors: { view: false},
  //   employee: {view:false, },
  //   booking: { view: false},
  //   financial: { view: false},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: true},
  //   systemSetting: { view: true},
  //   logSecurity: { view: true},
  // },

  // auditor: {
  //   dashboard: { view: true},
  //   users: { view: false},
  //   vendors: { view: false},
  //   employee: {view:false, },
  //   booking: { view: false},
  //   financial: { view: false},
  //   content: { view: false},
  //   reports: { view: false},
  //   marketing: { view: false},
  //   pushNotification: { view: false},
  //   support: { view: false},
  //   systemSetting: { view: false},
  //   logSecurity: { view: false},
  // }
};
